/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_astridweb_free: (a: number, b: number) => void;
export const __wbg_synctopicqueue_free: (a: number, b: number) => void;
export const astridweb_auditLen: (a: number) => any;
export const astridweb_auditTail: (a: number, b: number) => any;
export const astridweb_boot: () => any;
export const astridweb_check: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const astridweb_eventsRouted: (a: number) => bigint;
export const astridweb_grant: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const astridweb_guestKvGet: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const astridweb_guestKvSet: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => any;
export const astridweb_guestPublish: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const astridweb_hostKvCasSync: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number];
export const astridweb_hostKvClearPrefixSync: (a: number, b: number, c: number, d: number, e: number) => [bigint, number, number];
export const astridweb_hostKvDeleteSync: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const astridweb_hostKvGetSync: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const astridweb_hostKvListKeysSync: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const astridweb_hostKvSetSync: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const astridweb_hostPublish: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const astridweb_hostSubscribeQueue: (a: number, b: number, c: number) => number;
export const astridweb_kernelCommit: (a: number) => [number, number];
export const astridweb_kvGet: (a: number, b: number, c: number, d: number, e: number) => any;
export const astridweb_kvSet: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const astridweb_publish: (a: number, b: number, c: number, d: number, e: number) => any;
export const astridweb_revoke: (a: number, b: number, c: number) => any;
export const astridweb_subscribe: (a: number, b: number, c: number, d: any) => [number, number];
export const synctopicqueue_drain: (a: number) => [number, number];
export const synctopicqueue_dropped: (a: number) => bigint;
export const wasm_bindgen__convert__closures_____invoke__ha8fa1c53dd88e045: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h31c7c599dadf562f: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h5f67eaaf67bea9fb: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
